"use client";
/**
 * The icon set the game draws from — Phosphor Icons (the same set the griddle app uses),
 * re-exported here so components import from one place and styling stays consistent.
 * Default weight/size is set once via <IconContext.Provider> in GameApp.
 */
export {
  IconContext,
  House,
  Backpack,
  Sparkle,
  Trophy,
  Coins,
  DotsThree,
  Fire,
  SkipForward,
  Cookie,
  Ticket,
  Medal,
  TextAa,
  BookOpen,
  MaskHappy,
  ArrowsLeftRight,
  ArrowsDownUp,
  Eye,
  Smiley,
  SmileyMeh,
  SmileyXEyes,
  SmileySad,
  Package,
  Star,
  Crown,
  Confetti,
  DiceFive,
  Gift,
  MagnifyingGlass,
  ShareNetwork,
  X,
  Basket,
  Sun,
  Wallet,
  CurrencyDollar,
  CircleNotch,
  CaretRight,
  Check,
  Plus,
  Lock,
  Question,
} from "@phosphor-icons/react";
