/**
 * Regenerate docs/economy.md from the verified economy module, so the published tables
 * are never hand-maintained — they are computed from the canonical dictionary.
 *   npm run derive
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { WORD_COUNT } from "../src/lib/dictionary";
import {
  ALPHABET,
  LETTER_SLOTS,
  LETTER_ODDS,
  LETTER_SUPPLY_CAP,
  TOTAL_SLOTS,
  TOTAL_SUPPLY_CAP,
  LETTERS_BY_FREQUENCY,
  TIERS,
  TIER_COUNTS,
  LEGENDARIES,
  Q_WORDS,
  DOUBLED_ULTRA_RARES,
  wordsByTier,
} from "../src/lib/economy";

const pct = (n: number) => `${(n * 100).toFixed(2)}%`;

let md = `<!-- GENERATED by scripts/derive-economy.ts — do not edit by hand. Run \`npm run derive\`. -->
# Lexigotchi Economy (computed)

Derived from the canonical dictionary (\`data/guess_words_clean.ts\`, deduped) — the single
source of truth. These figures are asserted against spec Appendices A & B in
\`tests/economy.test.ts\`.

- **Eligible words:** ${WORD_COUNT.toLocaleString()}
- **Total letter slots:** ${TOTAL_SLOTS.toLocaleString()} (= ${WORD_COUNT} × 5)
- **Total minted-letter supply cap:** ${TOTAL_SUPPLY_CAP.toLocaleString()} (Σ floor(slots × 2.5))
  - Note: the spec prose headlines **55,475** = the idealized 2.5 × 22,190 *before* per-letter
    flooring. The deployable per-ID caps sum to **${TOTAL_SUPPLY_CAP.toLocaleString()}**, matching the spec's own
    Appendix A per-letter column.

## Appendix A — Letter economy

Mint odds = a letter's share of the ${TOTAL_SLOTS.toLocaleString()} slots. Supply cap = floor(slots × 2.5).

| Letter | Slots | Mint odds | Supply cap (2.5×) |
|---|---:|---:|---:|
`;

for (const L of LETTERS_BY_FREQUENCY) {
  md += `| ${L} | ${LETTER_SLOTS[L].toLocaleString()} | ${pct(LETTER_ODDS[L])} | ${LETTER_SUPPLY_CAP[L].toLocaleString()} |\n`;
}

md += `
**Q is the system's Charizard:** ${LETTER_SLOTS.Q} slots across the whole dictionary
(${Q_WORDS.length} Q-words; RAQQA needs two). The doubled-ultra-rare grails:
${DOUBLED_ULTRA_RARES.join(", ")}.

## Appendix B — Rarity tiers

Word rarity score = −Σ log₁₀(letter frequency) over its 5 letters; tiers cut at the
50th / 80th / 95th / 99th percentiles (floor cuts, alphabetical tiebreak).

| Tier | Words | Share | Stake weight |
|---|---:|---:|---:|
`;

for (const t of TIERS) {
  const count = TIER_COUNTS[t.name];
  md += `| ${t.name} | ${count.toLocaleString()} | ${pct(count / WORD_COUNT)} | ${t.weight} |\n`;
}

md += `
> Note: a single word sits on the Uncommon/Rare score-tie boundary, so the computed split is
> ${TIER_COUNTS.Uncommon}/${TIER_COUNTS.Rare} vs the spec's 1330/667 — the combined 1,997 is invariant; the anchor
> counts (Common ${TIER_COUNTS.Common}, Epic ${TIER_COUNTS.Epic}, Legendary ${TIER_COUNTS.Legendary}) match exactly.

### The ${LEGENDARIES.length} Legendaries (rarest first)

${LEGENDARIES.join(", ")}.

### All ${Q_WORDS.length} Q-words

${[...Q_WORDS].sort().join(", ")}.

### Cheapest starter words (most common letters)

${wordsByTier("Common").slice(-12).reverse().join(", ")} … (Common tier, ${TIER_COUNTS.Common.toLocaleString()} words)
`;

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "docs", "economy.md");
writeFileSync(out, md);
console.log(`wrote ${out} (${md.length} bytes)`);
