/**
 * Derive the app's typed contract ABIs from the Foundry build artifacts.
 *
 * Source of truth is `contracts/out/<C>.sol/<C>.json` (run `npm run contracts:build` first), so the
 * app can never drift from the compiled contracts — the failure mode this prevents is a hand-copied
 * ABI that still encodes after a signature changes, producing a transaction that reverts on-chain
 * for no visible reason.
 *
 * Emits `src/lib/onchain/abis.ts` with each ABI `as const`, which is what gives viem its full
 * argument-type inference at the call sites.
 *
 * Run: npm run derive:abis
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** The suite, in deploy order — matches src/lib/admin/deployments.ts ContractKey. */
const CONTRACTS = [
  ["feeRouter", "FeeRouter"],
  ["letters", "Letters"],
  ["words", "Words"],
  ["rolls", "Rolls"],
  ["staking", "Staking"],
  ["prestige", "Prestige"],
  ["answerChain", "AnswerChain"],
  ["jackpot", "Jackpot"],
  ["yieldDistributor", "YieldDistributor"],
  ["bounty", "Bounty"],
] as const;

/** Only the fragments the app actually calls — a full ERC-20 ABI is dead weight in the bundle. */
const ERC20_MIN = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  // MockERC20 only (Sepolia stand-in) — a permissionless faucet, absent on the real mainnet token.
  { type: "function", name: "mint", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
];

function abiOf(name: string): unknown[] {
  const path = resolve(ROOT, `contracts/out/${name}.sol/${name}.json`);
  if (!existsSync(path)) {
    throw new Error(`Missing artifact ${path}. Run: npm run contracts:build`);
  }
  const artifact = JSON.parse(readFileSync(path, "utf8"));
  if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) {
    throw new Error(`Artifact ${name} has no abi — is the build stale?`);
  }
  return artifact.abi;
}

const parts: string[] = [
  "/**",
  " * GENERATED by scripts/derive-abis.ts — do not edit.",
  " * Source: contracts/out/<C>.sol/<C>.json (Foundry). Regenerate with `npm run derive:abis`",
  " * after any contract change, or the app will encode against a stale signature.",
  " */",
  "",
];

for (const [key, name] of CONTRACTS) {
  parts.push(`export const ${key}Abi = ${JSON.stringify(abiOf(name))} as const;`, "");
}
parts.push(`export const erc20Abi = ${JSON.stringify(ERC20_MIN)} as const;`, "");

// The two operator approvals the game needs: Letters(1155) → Words, and Words(721) → Staking.
parts.push(
  `export const erc1155ApprovalAbi = ${JSON.stringify([
    { type: "function", name: "setApprovalForAll", stateMutability: "nonpayable", inputs: [{ name: "operator", type: "address" }, { name: "approved", type: "bool" }], outputs: [] },
    { type: "function", name: "isApprovedForAll", stateMutability: "view", inputs: [{ name: "account", type: "address" }, { name: "operator", type: "address" }], outputs: [{ type: "bool" }] },
  ])} as const;`,
  "",
);

parts.push(
  "export const ABIS = {",
  ...CONTRACTS.map(([key]) => `  ${key}: ${key}Abi,`),
  "} as const;",
  "",
);

const out = resolve(ROOT, "src/lib/onchain/abis.ts");
writeFileSync(out, parts.join("\n"));

const total = CONTRACTS.reduce((n, [, name]) => n + abiOf(name).length, 0);
console.log(`✓ src/lib/onchain/abis.ts`);
console.log(`  ${CONTRACTS.length} contracts, ${total} ABI entries`);
